servos.P2.setRange(0, 180)
servos.P1.setRange(0, 180)
servos.P0.setRange(0, 180)
basic.forever(function on_forever() {
    basic.showIcon(IconNames.Happy)
})
input.onButtonPressed(Button.A, function on_button_pressed_a() {
    servos.P2.setAngle(90)
    servos.P1.setAngle(180)
    servos.P0.setAngle(90)
    pins.servoWritePin(AnalogPin.P9, 90)
    pins.servoWritePin(AnalogPin.P8, 180)
})
input.onButtonPressed(Button.B, function on_button_pressed_b() {
    servos.P2.setAngle(0)
    servos.P1.setAngle(0)
    servos.P0.setAngle(0)
    pins.servoWritePin(AnalogPin.P8, 0)
    pins.servoWritePin(AnalogPin.P9, 0)
})
